# Generated by Django 2.2.8 on 2020-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11)),
                ('fone', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=12)),
                ('funcao', models.CharField(max_length=50)),
                ('admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refeicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('cep', models.CharField(max_length=12)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
