# Generated by Django 2.2.8 on 2020-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_adiantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
