# Generated by Django 2.2.8 on 2020-01-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_auto_20200101_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
