# Generated by Django 2.2.8 on 2020-01-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_auto_20200101_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adiantamento',
        ),
    ]
