# Generated by Django 2.2.8 on 2020-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_delete_adiantamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
