# Generated by Django 2.2.8 on 2020-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_auto_20200126_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/foto/'),
        ),
    ]
