# Generated by Django 2.2.8 on 2020-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20191005_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/%y/%m/%d/'),
        ),
    ]
