# Generated by Django 2.2.8 on 2020-01-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20200126_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, upload_to='produtos/'),
        ),
    ]
