# Generated by Django 2.2.8 on 2020-01-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20190905_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
